src/school/urls.py
from django.conf.urls.defaults import *
from school import views

urlpatterns = patterns('',
    (r'^(\w+)/$', views.home),
    (r'^(\w+)/assignments/$', views.assignments),
    (r'^(\w+)/assignment/(\d+)/$', views.assignment),
    (r'^(\w+)/attempt/feedback/$', views.attempt_feedback),#TODO: change to appropriate url
    (r'^(\w+)/video/list/$', views.video_list),
    (r'^(\w+)/progress/$', views.progress),
    (r'^(\w+)/schedule/$', views.schedule),
    (r'^(\w+)/materials/$', views.materials),
    (r'^(\w+)/faq/$', views.faq),
    (r'^(\w+)/qna/$', views.qna),
    (r'^(\w+)/preferences/$', views.preferences),
    (r'^(\w+)/change_name/$', views.change_name),
    (r'^(\w+)/change_password/$', views.change_password),
    (r'^(\w+)/change_email/$', views.change_email),
    (r'^(\w+)/change_pref/$', views.change_pref),
)

src/school/models.py
from django.db import models
from django.contrib.auth.models import User

class Student(models.Model):
    user = models.ForeignKey(User, unique=True)
    email = models.BooleanField()

class Faq(models.Model):
    html = models.TextField()

class Schedule(models.Model):
    html = models.TextField()

class Course(models.Model):
    name = models.CharField(max_length=100)
    schedule = models.ForeignKey(Schedule)
    faq = models.ForeignKey(Faq)
    slug = models.SlugField(unique=True)

    def __unicode__(self):
        return self.name

class LectureCategory(models.Model):
    name = models.CharField(max_length=100)
    course = models.ForeignKey(Course)
    due = models.DateTimeField()

    def __unicode__(self):
        return self.name
    def is_viewed(self, user):
        viewed = True
        lectures = self.lecture_set.all()
        for lecture in lectures:
            if not lecture.is_viewed(user):
                viewed = False
                break
        return viewed

class Lecture(models.Model):
    name = models.CharField(max_length=100)
    youtube_id = models.CharField(max_length=100)
    course = models.ForeignKey(Course)
    category = models.ForeignKey(LectureCategory)
    recommended_literature = models.TextField(blank=True)

    def __unicode__(self):
        return self.name
    def get_users(self):
        return self.lectureattempt_set.values_list('student', flat=True)
    def is_viewed(self, user):
        return self.lectureattempt_set.count() > 0

class Assignment(models.Model):
    name = models.CharField(max_length=100)
    due = models.DateTimeField()
    course = models.ForeignKey(Course)
    max_points = models.FloatField()
    prerequisite = models.ForeignKey(LectureCategory)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.name
    def get_attempts(self, user):
        return self.attempt_set.filter(student=user)
    def get_users(self):
        return self.attempt_set.values_list('student', flat=True)
    @models.permalink
    def get_absolute_url(self):
        return ('school.views.assignment', [self.course.slug, str(self.id)])

class Question(models.Model):
    text = models.TextField()
    quiz = models.ForeignKey(Assignment)
    variants = models.TextField()
    answer = models.CharField(max_length=30)
    explanation = models.TextField(blank=True)

class Attempt(models.Model):
    student = models.ForeignKey(User)
    assignment = models.ForeignKey(Assignment)
    date = models.DateTimeField()
    points = models.FloatField()

class LectureAttempt(models.Model):
    student = models.ForeignKey(User)
    lecture = models.ForeignKey(Lecture)
    date = models.DateTimeField()

class Announcement(models.Model):
    """Anouncement model, all anouncements will be
       displaied on course home screen"""
    date = models.DateField()
    text = models.TextField()
    assignment = models.BooleanField()
    course = models.ForeignKey(Course)

    def __unicode__(self):
        return self.text

class Material(models.Model):
    url = models.URLField(max_length=300)
    name = models.CharField(max_length=200)
    lecture = models.ForeignKey(Lecture)

    def __unicode__(self):
        return self.name

src/school/templates/school/assignment.html
{% extends "school/base.html" %}
{% load i18n %}

{% block title %}{% trans "School" %} - {% trans "Homepage" %}{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
<h2>{{ assignment.name }}</h2>
<div class="row" style="margin: 20px;">
<div class="span4" style="font-weight:bold; text-align: right;">
  Due<br />
  Attempts made<br />
</div>
<div class="span6">
  {{ assignment.due|date:"D, M j G:i T" }}<br />
  {{ attempts_count }}<br />
</div>
</div>
<p style="margin: 20px;">The assignment will begin immediately after you click on Start button below. Good luck!</p>
<form method="post" action="">
  {% csrf_token %}
  <input type="hidden" name="action" value="start" />
  <input type="submit" class="btn" style="margin-left: 20px;" value="Click here to start" />
</form>
{% endblock %}

src/school/templates/school/assignment_list.html
{% extends "school/base.html" %}
{% load i18n school_extras %}

{% block title %}{% trans "School" %} - {% trans "Homepage" %}{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
<div class="page-header">
  <h1>Assignments</h1>
</div>
<div class="assignments-info">
<!--following text should contain info or recomendations about assignments-->
The quizzes and exercises may be attempted as many times as you like. We will use the highest score you achieve, so we certainly recommend you retake each one until you receive full credit. (In fact, for the quizzes you'll get a different variant of each problem on every attempt, so you may want to continue using them for practice even after you've achieved full credit.) After the deadline you may continue to take the quizzes and perform the exercises -- either for practice or because you didn't complete them on time. However, because we may offer partial solutions for some problems after the deadline (for educational purposes), scores on after-deadline attempts are penalized 50%. 
</div>
{% for assignment in assignment_list %}
  <div class="row assignments">
    <div class="span2 ass-icon"><img src="{{ STATIC_URL }}school/img/quiz_48.png"/></div>
    <div class="span9 ass-item">
      <a href="{{ assignment.get_absolute_url }}">
        <h3>{{ assignment.name }}
          <span class="pull-right">[Attempt]</span>
        </h3>
      </a>
      {% with i=forloop.counter0 %}
        {% if attempts|get_item:i %}
          {% with last_attempt=attempts|get_item:i|get_last_item %}
            <div class="ass-status">Last attempted at {{ last_attempt.date|date:"D, M j G:i T" }}</div>
          {% endwith %}
          <table class="ass-attempts">
            <thead>
              <tr>
                <th>#</th>
                <th>Saved/submitted at</th>
                <th>Score</th>
              </tr>
            </thead>
            <tbody>
              {% for attempt in attempts|get_item:i %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>Submitted {{ attempt.date|date:"D, M j G:i T" }}</td>
                  <td><a href="#">{{ attempt.points|floatformat:2 }}/{{ assignment.max_points }}</a></td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <div class="ass-status">Not attempted</div>
        {% endif %}
      {% endwith %}
      <small>Due: {{ assignment.due|date:"D, M j G:i T" }}</small>
    </div>
  </div>
{% endfor %}
{% endblock %}

src/school/templates/school/attempt.html
{% extends "school/base.html" %}
{% load i18n school_extras %}

{% block title %}{% trans "School" %} - {% trans "Homepage" %}{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
<div class="assignment">
  <h2>Assignment name</h2>
  <div class="info">
    {{ assignment.description }}
  </div>

  <form action="" method="post">
    {% csrf_token %}
    <input type="hidden" name="action" value="end" />
    <fieldset>
      {% for question in assignment.question_set.all %}
        <div class="question">
          <h3>Question {{ forloop.counter }}</h3>
          <pre>{{ question.text }}</pre>
          <div class="clearfix">
            {% if question.variants|lines|length > 1 %}
            <ul class="inputs-list">
              {% if question.answer|split:","|length > 1 %}
                {% for variant in question.variants|lines %}
                  <li>
                    <label>
                      <input type="checkbox" name="q{{ forloop.parentloop.counter }}" value="{{ forloop.counter }}" />
                      <span>{{ variant }}</span>
                    </label>
                  </li>
                {% endfor %}
              {% else %}
                {% for variant in question.variants|lines %}
                  <li>
                    <label>
                      <input type="radio" name="q{{ forloop.parentloop.counter }}" value="{{ forloop.counter }}" />
                      <span>{{ variant }}</span>
                    </label>
                  </li>
                {% endfor %}
              {% endif %}
            </ul>
            {% else %}
              <input class="span7" name="q{{ forloop.counter }}" />
            {% endif %}
          </div>
        </div>
      {% endfor %}
      <div class="actions">
        <input type="submit" class="btn primary" value="Submit for grading">
      </div>
    </fieldset>
  </form>
</div>
{% endblock %}

src/school/templates/school/attempt_feedback.html
{% extends "school/base.html" %}
{% load i18n school_extras %}

{% block title %}{% trans "School" %} - {% trans "Homepage" %}{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
<div class="assignment">
  <h2>Assignment name</h2>
  <p>
    You achieved a score of {{ total|floatformat:2 }} out of {{ assignment.max_points|floatformat:2 }}
  </p>
  <div class="info">
    {{ assignment.description }}
  </div>
  <form>
    <fieldset>
      {% for question in assignment.question_set.all %}
        <div class="question">
          <h3>Question {{ forloop.counter }}</h3>
          <pre>{{ question.text }}</pre>
          <div class="clearfix">
            {% if question.variants|lines|length > 1 %}
            <ul class="inputs-list">
              {% if question.answer|split:","|length > 1 %}
                {% for variant in question.variants|lines %}
                  <li class="disabled">
                    <label>
                      <input type="checkbox" {% if forloop.counter in answers|get_checkbox_item:forloop.parentloop.counter %}checked {% endif %}name="q{{ forloop.parentloop.counter }}" value="{{ forloop.counter }}" disabled/>
                      <span>{{ variant }}</span>
                    </label>
                  </li>
                {% endfor %}
              {% else %}
                {% for variant in question.variants|lines %}
                  <li class="disabled">
                    <label>
                      <input type="radio" {% ifequal answers|get_radio_item:forloop.parentloop.counter forloop.counter %}checked {% endifequal %}name="q{{ forloop.parentloop.counter }}" value="{{ forloop.counter }}" disabled />
                      <span>{{ variant }}</span>
                    </label>
                  </li>
                {% endfor %}
              {% endif %}
            </ul>
            {% else %}
              <input class="span7" name="q{{ forloop.counter }}" value="{{ answers|get_text_item:forloop.counter }}" disabled/>
            {% endif %}
          </div>
          <table>
            <thead>
              <tr>
                <th>Your answer</th>
                <th>Score</th>
                <th width="45%">Choice explanation</th>
              </tr>
            </thead>
            <tbody>
              {% if question.variants|lines|length > 1 %}
                {% if question.answer|split:","|length > 1 %}
                  {% with answers|get_checkbox_item:forloop.counter as answer %}
                  <tr>
                    <td>
                      {% for ans in answer %}
                        {{ question.variants|lines|get_item0:ans }}<br />
                      {% endfor %}
                    </td>
                    <td>
                      {% ifequal question.answer|split:","|list_to_int answer %}
                        {{ points|floatformat:2 }}
                      {% else %}0{% endifequal %}
                    </td>
                    <td>{{ question.explanation }}</td>
                  </tr>
                  {% endwith %}
                {% else %}
                  {% with answers|get_radio_item:forloop.counter as answer %}
                  <tr>
                    <td>{{ question.variants|lines|get_item0:answer }}</td>
                    <td>{% ifequal question.answer|to_int answer %}{{ points|floatformat:2 }}{% else %}0{% endifequal %}</td>
                    <td>{{ question.explanation }}</td>
                  </tr>
                  {% endwith %}
                {% endif %}
              {% else %}
                <tr>
                  {% with answers|get_text_item:forloop.counter as answer %}
                  <td>{{ answer }}</td>
                  <td>{% ifequal question.variants answer %}{{ points|floatformat:2 }}{% else %}0{% endifequal %}</td>
                  <td>{{ question.explanation }}</td>
                  {% endwith %}
                </tr>
              {% endif %}
            </tbody>
          </table>
        </div>
      {% endfor %}
    </fieldset>
  </form>
</div>

{% endblock %}

src/school/templates/school/base.html
{% load i18n %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>{% block title %}{% endblock %}</title>
    <script type="text/javascript" src="{{ STATIC_URL }}school/js/jquery-1.5.1.min.js"></script>
    <link rel="stylesheet/less" href="{{ STATIC_URL }}school/css/main.less" type="text/css" />
    <script type="text/javascript" src="{{ STATIC_URL }}school/js/less-1.1.3.min.js"></script>
    {% block header %}{% endblock %}
</head>
<body>
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="{% url school.views.home course %}">{{ course_name }}</a>
          {% if user.is_authenticated %}
          <div  class="pull-right user-menu">
            <a href="{% url school.views.preferences course %}">{{ user }}</a>
            <a href="/accounts/logout/">Logout</a>
          </div>
          {% else %}
          <form method="post" action="/accounts/login/?next=/school" class="pull-right">
            {% csrf_token %}
            <input class="input-small" type="text" name="username" placeholder="Username">
            <input class="input-small" type="password" name="password" placeholder="Password">
            <button class="btn" type="submit">Sign in</button>
          </form>
          {% endif %}
        </div>
      </div>
    </div>
  <div class="container">

      <div class="content">
        <div class="row">
          <div class="span4">
            <ul class="left-menu pills">
              <li {% if home %}class="active"{% endif %}><a href="{% url school.views.home course %}">{% trans "Home" %}</a></li>
              <li {% if assignments %}class="active"{% endif %}><a href="{% url school.views.assignments course %}">{% trans "Assignments" %}</a></li>
              <li {% if video_list%}class="active"{% endif %}><a href="{% url school.views.video_list course %}">{% trans "Video Lectures" %}</a></li>
              <li {% if progress %}class="active"{% endif %}><a href="{% url school.views.progress course %}">{% trans "Course Progress" %}</a></li>
              <li {% if schedule %}class="active"{% endif %}><a href="{% url school.views.schedule course %}">{% trans "Course Schedule" %}</a></li>
              <li {% if materials %}class="active"{% endif %}><a href="{% url school.views.materials course %}">{% trans "Course Materials" %}</a></li>
              <li {% if faq %}class="active"{% endif %}><a href="{% url school.views.faq course %}">{% trans "FAQ" %}</a></li>
              <li {% if qna %}class="active"{% endif %}><a href="{% url school.views.qna course %}">{% trans "QA Forum" %}</a></li>
            </ul>
          </div>
          <div class="span11">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>

      <footer>
        <p>&copy; Giylem 2011</p>
      </footer>

    </div> <!-- /container -->
</body>
</html>

src/school/templates/school/faq.html
{% extends "school/base.html" %}
{% load i18n %}

{% block title %}{% trans "School" %} - {% trans "Homepage" %}{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
        <div class="page-header">
          <h1>FAQ <small>frequently asked questions</small></h1>
        </div>

        <div class="faq-section">
          {{ faq_html|safe }}
        </div>
{% endblock %}

src/school/templates/school/home.html
{% extends "school/base.html" %}
{% load i18n %}

{% block title %}{% trans "School" %} - {% trans "Homepage" %}{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
  <div class="page-header">
    <h1>{% trans "What's new" %} <small>{% trans "Here you can see last updates and news" %}</small></h1>
  </div>
  {% regroup news by date as news_list %}
  {% for item in news_list %}
    <div class="course-news">
      <h3>{{ item.grouper|date:"l, d F Y" }}</h3>
      {% for announcement in item.list %}
        <div class="course-announcement row">
          <div class="span2 news-icon"><img src="{{ STATIC_URL }}school/img/{% if announcement.assignment %}quiz{% else %}home{% endif %}_48.png"/></div>
          <div class="span9 news-text">
            {{ announcement.text|safe }}
          </div>
        </div>
      {% endfor %}
    </div>
  {% endfor %}
{% endblock %}

src/school/templates/school/materials.html
{% extends "school/base.html" %}
{% load i18n %}
{% load school_extras %}

{% block title %}{% trans "School" %} - {% trans "Homepage" %}{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
<div class="page-header">
  <h1>Course materials</h1>
</div>
<!-- Couple words about materials -->
<p>Course materials are specified corresponding to the videos, in order by topic. For each video, you can download the slides in Powerpoint (<img width="25" height="25" src="{{ STATIC_URL }}school/img/pptx-icon.png"/>) or in PDF (<img width="25" height="25" src="{{ STATIC_URL }}school/img/pdf-icon.png"/>), and we also provide any files used in SQL or XML demonstrations (<img width="25" height="25" src="{{ STATIC_URL }}school/img/file-icon.png"/>).</p>
{% for category in categories %}
<h2>{{ category.name }}</h3>
<table class="lecture-materials">
  <tbody>
    {% for lecture in category.lecture_set.all %}
    <tr>
      <td class="left-col">
        <h3>{{ lecture.name }}</h3>
        <div class="materials list">
          <ul><!-- Provide required sections -->
            {% for book in lecture.recommended_literature|lines %}
              <li>{{ book }}</li>
            {% endfor %}
          </ul>
        </div>
      </td>
      <td class="right-col">
        <div class="materials icons pull-right">
          {% for material in lecture.material_set.all %}
            <a href="{{ material.url }}" class="file">
              <img alt="{{ material.name }}" title="{{ material.name }}" src="{{ STATIC_URL }}school/img/{{ material.url|material }}-icon.png"/>
            </a>
          {% endfor %}
        </div>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endfor %}
{% endblock %}

src/school/templates/school/preferences.html
{% extends "school/base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "School" %} - {% trans "Homepage" %}{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
        <div class="page-header">
          <h1>{% trans "Preferences" %}</h1>
        </div>
       <div class="preferences">
        {% for message in messages %}
          <div class="alert-message {{ message.tags }}">
            <p>{{ message }}</p>
          </div>
        {% endfor %}
          <h4>Announcement Preferences</h4>
          <form method="post" action="{% url school.views.change_pref course %}">
            {% csrf_token %}
            <div class="clearfix">
              <label id="optionsCheckboxes">Staff Emails</label>
              <div class="input">
                <label class="span8" style="margin-left:0px;">
                  <input type="checkbox" name="stuff_email" {% if stuff_email %}checked{% endif %}>
                  <span>Yes, email me when there is an announcement from the course staff.</span>
                </label>
              </div>
            </div>
            <div class="actions">
              <input type="submit" class="btn primary" value="Save preferences" />
            </div>
          </form>
          <h4>Change Full Name</h4> 
          <form method="post" action="{% url school.views.change_name course %}">
            {% csrf_token %}
            <div class="clearfix">
              <label for="name">Name</label>
              <div class="input">
                <input class="span4" id="name" name="name" type="text" value="{{ user.first_name }}">
              </div>
            </div>
            <div class="clearfix">
              <label for="surname">Surname</label>
              <div class="input">
                <input class="span4" id="surname" name="surname" type="text" value="{{ user.last_name }}">
              </div>
            </div>
            <div class="actions">
              <input type="submit" class="btn primary" value="Change name" />
            </div>
          </form>
          <h4>Change Password <small>The password change takes effect immediately.</small></h4>
          <form method="post" action="{% url school.views.change_password course %}">
            {% csrf_token %}
            <div class="clearfix">
              <label for="currpass">Current Password</label>
              <div class="input">
                <input type="password" class="span4" id="currpass" name="currpass" type="text" />
              </div>
            </div>
            <div class="clearfix">
              <label for="newpass">New Password</label>
              <div class="input">
                <input type="password" class="span4" id="newpass" name="newpass" type="text" />
              </div>
            </div>
            <div class="clearfix">
              <label for="retypepass">Password (again)</label>
              <div class="input">
                <input type="password" class="span4" id="retypepass" name="retypepass" type="text" />
              </div>
            </div>
            <div class="actions">
              <input type="submit" class="btn primary" value="Change password" />
            </div>
          </form>
          <h4>Change Email Address</h4> 
          <form method="post" action="{% url school.views.change_email course %}">
            {% csrf_token %}
            <div class="clearfix">
              <label for="newemail">New Email</label>
              <div class="input">
                <input class="span4" id="newemail" name="newemail" type="text" />
              </div>
            </div>
            <div class="clearfix">
              <label for="retypeemail">Email (again)</label>
              <div class="input">
                <input class="span4" id="retypeemail" name="retypeemail" type="text" />
              </div>
            </div>
            <div class="actions">
              <input type="submit" class="btn primary" value="Change email address" />
            </div>
          </form>
       </div>
        
{% endblock %}

src/school/templates/school/progress.html
{% extends "school/base.html" %}
{% load i18n %}

{% block title %}{% trans "School" %} - {% trans "Homepage" %}{% endblock %}

{% block header %}
<script type="text/javascript" src="http://twitter.github.com/bootstrap/1.3.0/bootstrap-modal.js"></script>
    <script>
 $(document).ready(function(){
    $('.progress-header').bind('click',function() {
      $(this).next('ul').slideToggle('slow');
    });
    $('.subsection-title').bind('click',function() {
      $(this).next('ul').slideToggle('slow');
    });
 });
    </script>
{% endblock %}

{% block content %}
        <div class="page-header">
          <h1>Course Progress</h1>
        </div>
<div class="progress-section completed">
  <div class="progress-header completed">
    <h2><img src="{{ STATIC_URL }}school/img/progress_done_32.png" />Completed</h2>
  </div>
  <ul style="display:none;">
    {% for object in completed_list %}
      <li>
        {% if object.max_points %}
          <img class="icon24" src="{{ STATIC_URL }}school/img/quiz_24.png"/>
          <a href="#">{{ object.name }}</a><span class="pull-right">Due {{ object.due|date:"D, M j G:i T" }}</span>
        {% else %}
        <div class="subsection-title">
          <img class="icon24" src="{{ STATIC_URL }}school/img/video_24.png" />{{ object.name }}
        </div>
        <ul>
          {% for lecture in object.lecture_set.all %}
            <li {% if user.id in lecture.get_users %}class="viewed"{% endif %}>
              <a href="#" data-controls-modal="video-modal" data-backdrop="static">{{ lecture.name }}</a>
            </li>
          {% endfor %}
        </ul>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
</div>

<div class="progress-section in-progress">
  <div class="progress-header in-progress">
    <h2><img src="{{ STATIC_URL }}school/img/progress_current_32.png" />In Progress</h2>
  </div>
  <ul>
    {% for object in in_progress_list %}
      <li>
        {% if object.max_points %}
          <img class="icon24" src="{{ STATIC_URL }}school/img/quiz_24.png"/>
          <a href="#">{{ object.name }}</a><span class="pull-right">Due {{ object.due|date:"D, M j G:i T" }}</span>
        {% else %}
        <div class="subsection-title">
          <img class="icon24" src="{{ STATIC_URL }}school/img/video_24.png" />{{ object.name }}
        </div>
        <ul>
          {% for lecture in object.lecture_set.all %}
            <li class="video-lecture{% if user.id in lecture.get_users %} viewed{% endif %}" video-id="{{lecture.youtube_id}}">{{ lecture.name }}</li>
          {% endfor %}
        </ul>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
</div>

<div class="progress-section next-up">
  <div class="progress-header next-up">
    <h2><img src="{{ STATIC_URL }}school/img/progress_next_32.png" />Next Up</h2>
  </div>
  <ul style="display:none;">
    {% for object in next_up_list %}
      <li>
        {% if object.max_points %}
          <img class="icon24" src="{{ STATIC_URL }}school/img/quiz_24.png"/>
          <a href="#">{{ object.name }}</a><span class="pull-right">Due {{ object.due|date:"D, M j G:i T" }}</span>
        {% else %}
        <div class="subsection-title">
          <img class="icon24" src="{{ STATIC_URL }}school/img/video_24.png" />{{ object.name }}
        </div>
        <ul>
          {% for lecture in object.lecture_set.all %}
            <li {% if user.id in lecture.get_users %}class="viewed"{% endif %}>
              <a href="#" data-controls-modal="video-modal" data-backdrop="static">{{ lecture.name }}</a>
            </li>
          {% endfor %}
        </ul>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
</div>
<!-- Video player includes here -->
{% include "school/video_modal.html" %}
{% endblock %}

src/school/templates/school/qna.html
{% extends "school/base.html" %}
{% load i18n %}

{% block title %}{% trans "School" %} - {% trans "Homepage" %}{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
        <div class="page-header">
          <h1>Page name <small>Supporting text or tagline</small></h1>
        </div>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat
{% endblock %}

src/school/templates/school/schedule.html
{% extends "school/base.html" %}
{% load i18n %}

{% block title %}{% trans "School" %} - {% trans "Homepage" %}{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
        <div class="page-header">
          <h1>Course schedule</h1>
        </div>
        <div class="schedule-html">
          {{ schedule_html|safe }}
        </div>
{% endblock %}

src/school/templates/school/video_list.html
{% extends "school/base.html" %}
{% load i18n %}

{% block title %}{% trans "School" %} - {% trans "Homepage" %}{% endblock %}

{% block header %}
<script type="text/javascript" src="http://twitter.github.com/bootstrap/1.3.0/bootstrap-modal.js"></script>
{% endblock %}

{% block content %}
    <script>
 $(document).ready(function(){
    $('.expand-control').parent().bind('click',function() {
      $(this).next('ul').slideToggle('slow');
      $(this).children('.expand-control').toggleClass('expanded');
    });
 });
    </script>
    <div class="page-header">
      <h1>Video Lectures</h1>
    </div>
    <div class="lecture-list">
      {% for category in categories %}
        <div class="section">
          <h3>
              <div class="expand-control"> </div>
              <div class="section-title">{{ category.name }}</div>
          </h3>
          <ul style="display:none;">
            {% for lecture in category.lecture_set.all %}
              <li class="video-lecture{% if user.id in lecture.get_users %} viewed{% endif %}" video-id="{{lecture.youtube_id}}">{{ lecture.name }}</li>
            {% endfor %}
          </ul>
        </div>
      {% endfor %}
    </div>
    <!-- Video player includes here -->
    {% include "school/video_modal.html" %}
{% endblock %}

src/school/templates/school/video_modal.html
    <script>
 $(document).ready(function(){
    $('.video-lecture').bind('click',function() {
      var videoId = $(this).attr('video-id');
      var videoUrl = "http://www.youtube.com/v/"+videoId+"?version=3&autohide=1&showinfo=0";
      $('#movie').attr('value', videoUrl);
      $('#embed').attr('src', videoUrl);
      $('#video-modal').modal('show');
    });
    $('#video-modal').modal({
      keyboard: true,
      backdrop: true
    });
 });
    </script>
    <div id="video-modal" class="modal hide fade">
        <div class="modal-header">
          <a href="#" class="close">×</a>
          <h3>Modal Heading</h3>
        </div>
        <div class="modal-body">
          <object width="560" height="470">
            <param id="movie" name="movie"
              value="http://www.youtube.com/v/u1zgFlCw8Aw?version=3&autohide=1&showinfo=0"></param>
            <param name="allowScriptAccess" value="always"></param>
            <embed id="embed" src="http://www.youtube.com/v/u1zgFlCw8Aw?version=3&autohide=1&showinfo=0"
              type="application/x-shockwave-flash"
              allowscriptaccess="always"
              width="560" height="470"></embed>
          </object>
        </div>
        <div class="modal-footer">
            <a href="#">Previous</a>
            <a href="#" class="pull-right">Next</a>
        </div>
    </div>